import os
import yaml
import clip
import torch
import argparse
import sys
import ipdb

def load_xprompt_data(xprompt_file):
    """
    Load xprompt data from the YAML file generated by askg2xprompt.py
    """
    print(f"Loading xprompt data from {xprompt_file}...")
    try:
        with open(xprompt_file, 'r') as f:
            data = yaml.safe_load(f)
        return data
    except Exception as e:
        print(f"Error loading xprompt data: {e}")
        sys.exit(1)

def encode_with_clip(model, text_list, device, batch_size=256):
    """
    Encode a list of text with CLIP in batches
    """
    all_embeddings = []
    
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+batch_size]
        tokens = clip.tokenize(batch).to(device)
        with torch.no_grad():
            embeddings = model.encode_text(tokens)
        all_embeddings.append(embeddings.cpu())
    
    return torch.cat(all_embeddings)

def process_xprompt_data(xprompt_data, output_file, device='cuda'):
    """
    Process the xprompt data and encode with CLIP,
    maintaining the original structure but replacing text with embeddings
    """
    # Load CLIP model
    print(f"Loading CLIP model on {device}...")
    model, _ = clip.load("ViT-B/32", device=device)
    model.eval()
    
    # Prepare data structures
    all_prompts = []  # All unique prompts to encode
    prompt_to_idx = {}  # Mapping from prompt text to index
    
    # First pass: collect all unique prompts from both xprompt_ao and xprompt_aa
    print("Collecting all unique prompts...")
    for action_dict in xprompt_data:
        for action_name, action_info in action_dict.items():
            if 'xprompt_ao' in action_info:
                for prompt in action_info['xprompt_ao']:
                    if prompt not in prompt_to_idx:
                        prompt_to_idx[prompt] = len(all_prompts)
                        all_prompts.append(prompt)
            
            if 'xprompt_aa' in action_info:
                for prompt in action_info['xprompt_aa']:
                    if prompt not in prompt_to_idx:
                        prompt_to_idx[prompt] = len(all_prompts)
                        all_prompts.append(prompt)
    
    print(f"Found {len(all_prompts)} unique prompts to encode")
    
    # Encode all unique prompts at once for efficiency
    print("Encoding prompts with CLIP...")
    all_embeddings = encode_with_clip(model, all_prompts, device)
    print(f"Encoded features shape: {all_embeddings.shape}")
    
    # Second pass: replace prompts with embeddings while maintaining structure
    encoded_data = []
    
    for action_dict in xprompt_data:
        encoded_action_dict = {}

        for action_name, action_info in action_dict.items():
            encoded_action_info = {'label': action_info.get('label', action_name), 'idx': action_info.get('idx', action_name)}
            
            # Process xprompt_ao
            if 'xprompt_ao' in action_info:
                encoded_action_info['xprompt_ao'] = []
                for prompt in action_info['xprompt_ao']:
                    prompt_idx = prompt_to_idx[prompt]
                    encoded_action_info['xprompt_ao'].append({
                        'text': prompt,
                        'embedding': all_embeddings[prompt_idx]
                    })
            
            # Process xprompt_aa
            if 'xprompt_aa' in action_info:
                encoded_action_info['xprompt_aa'] = []
                for prompt in action_info['xprompt_aa']:
                    prompt_idx = prompt_to_idx[prompt]
                    encoded_action_info['xprompt_aa'].append({
                        'text': prompt,
                        'embedding': all_embeddings[prompt_idx]
                    })
        encoded_data.append(encoded_action_info)
    encoded_data = sorted(encoded_data, key=lambda x: x['idx'], reverse=False)
    ipdb.set_trace()
    # Save the encoded data and metadata
    print(f"Saving encoded data to {output_file}")
    torch.save({
        'encoded_data': encoded_data,  # Main data structure: list of action dictionaries
        'metadata': {
            'prompt_to_idx': prompt_to_idx,
            'all_prompts': all_prompts,
            'all_embeddings': all_embeddings
        }
    }, output_file)
    
    return encoded_data

def main():
    parser = argparse.ArgumentParser(description='Encode xprompts with CLIP')
    parser.add_argument('--input', type=str, default='ASKG/data/ntu/classes_xprompt_ntu.yml', 
                        help='Input YAML file with xprompt data')
    parser.add_argument('--output', type=str, default='ASKG/data/char_feats_ntu.tar', 
                        help='Output file for encoded features')
    parser.add_argument('--device', type=str, default='cuda' if torch.cuda.is_available() else 'cpu', 
                        help='Device to use for encoding')
    
    args = parser.parse_args()
    
    print(f"Using device: {args.device}")
    print(f"Input file: {args.input}")
    print(f"Output file: {args.output}")
    
    # Check if input file exists
    if not os.path.exists(args.input):
        print(f"Error: Input file '{args.input}' not found")
        sys.exit(1)
    
    # Load xprompt data
    xprompt_data = load_xprompt_data(args.input)
    
    if not xprompt_data:
        print("No data found in the input file")
        sys.exit(1)
    
    # Process and encode data
    encoded_data = process_xprompt_data(xprompt_data, args.output, args.device)
    
    # Print summary
    print("\nProcessing complete!")
    print(f"Encoded {len(encoded_data)} actions")
    
    # Print example of the first action's structure
    if encoded_data:
        first_dict = encoded_data[0]
        first_action = list(first_dict.keys())[0]
        first_info = first_dict[first_action]
        
        print(f"\nExample structure for action '{first_action}':")
        print(f"label: {first_info['label']}")
        
        if 'xprompt_ao' in first_info:
            print(f"xprompt_ao: {len(first_info['xprompt_ao'])} prompts")
            if first_info['xprompt_ao']:
                sample = first_info['xprompt_ao'][0]
                print(f"  Example: '{sample['text']}'")
                print(f"  Embedding shape: {sample['embedding'].shape}")
        
        if 'xprompt_aa' in first_info:
            print(f"xprompt_aa: {len(first_info['xprompt_aa'])} prompts")
            if first_info['xprompt_aa']:
                sample = first_info['xprompt_aa'][0]
                print(f"  Example: '{sample['text']}'")
                print(f"  Embedding shape: {sample['embedding'].shape}")

if __name__ == '__main__':
    main()